// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplicationBackEnd;

#nullable disable

namespace WebApplicationBackEnd.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220920013352_Datos")]
    partial class Datos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApplicationBackEnd.Entidades.Datos", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int?>("Videojuegoid")
                        .HasColumnType("int");

                    b.Property<string>("desarrolladores")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("genero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("plataformas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("primerlanzamiento")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Videojuegoid");

                    b.ToTable("Datos");
                });

            modelBuilder.Entity("WebApplicationBackEnd.Entidades.Videojuego", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Videojuegos");
                });

            modelBuilder.Entity("WebApplicationBackEnd.Entidades.Datos", b =>
                {
                    b.HasOne("WebApplicationBackEnd.Entidades.Videojuego", null)
                        .WithMany("datos")
                        .HasForeignKey("Videojuegoid");
                });

            modelBuilder.Entity("WebApplicationBackEnd.Entidades.Videojuego", b =>
                {
                    b.Navigation("datos");
                });
#pragma warning restore 612, 618
        }
    }
}
